### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'point_size'

### ISSUE THREAD

**Issue by SUPER-ALEX** [oakink/OakInk-Grasp-Generation#4]
(oishape_bm) root@autodl-container-5e5249940a-c4ef59ac:~/OakInk-Grasp-Generation# python scripts/grasp_new_obj.py --obj_path assets/hand_mesh_watertight.obj --n_grasps 10 

2024-05-14 00:21:21,823 [   INFO] Using 1 GPUS
2024-05-14 00:21:21,981 [   INFO] => Loading CoarseNet pretrained model from: checkpoints/grabnet_oishape/CoarseNet.pth.tar
2024-05-14 00:21:22,026 [   INFO] => Loading SUCCEEDED
2024-05-14 00:21:22,128 [   INFO] => Loading RefineNet pretrained model from: checkpoints/grabnet_oishape/RefineNet.pth.tar
2024-05-14 00:21:22,143 [   INFO] => Loading SUCCEEDED
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
Traceback (most recent call last):
  File "/root/OakInk-Grasp-Generation/scripts/grasp_new_obj.py", line 173, in <module>
    grasp_new_obj(arg, exp_time)
  File "/root/OakInk-Grasp-Generation/scripts/grasp_new_obj.py", line 110, in grasp_new_obj
    viz_ctx.init()
  File "/root/OakInk-Grasp-Generation/lib/viztools/viz_o3d_utils.py", line 57, in init
    self.vis.get_render_option().point_size = point_size
AttributeError: 'NoneType' object has no attribute 'point_size'

**Comment by lixiny** [comment]
The error is traced back to open3D: 

[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW

you need to either start  X11 server or plug a screen on you machine.
